services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 42069:42069
    environment:
      PONDER_LOG_LEVEL: trace
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      DATABASE_SCHEMA: test
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    