name: Health Check and Notify

on:
  schedule:
    # Runs every hour on the hour
    - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ping placeholder health check endpoint
        id: ping
        run: |
          # This command sends a request and outputs only the HTTP status code.
          # -L follows redirects.
          # -s runs in silent mode.
          # -o /dev/null discards the response body.
          # -w "%{http_code}" prints the status code to stdout.
          # Replace the URL with your actual health check endpoint.
          STATUS_CODE=$(curl -L -s -o /dev/null -w "%{http_code}" https://YOUR_HEALTHCHECK_ENDPOINT)
          
          # Make the status code available to subsequent steps
          echo "STATUS_CODE=$STATUS_CODE" >> $GITHUB_ENV

      - name: Trigger action endpoint on 200 status
        if: env.STATUS_CODE == '200'
        run: |
          echo "Health check successful with status 200. Triggering action endpoint."
          # This command sends a POST request to your action endpoint.
          # Replace the URL with your actual action endpoint.
          curl -X POST https://YOUR_ACTION_ENDPOINT 